Final report api
CapeSoftwareTeam/Cape-Electric-Software-BackEnd pull request #24
Opened 2021-06-21 14:57 UTC by thirumoorthy2005

I have created finalReportAPI

2021-06-21 15:03 UTC, thirumoorthy2005 commented
finalReportAPI created  successfully

2021-06-21 15:12 UTC, CapeSathish requested changes

2021-06-21 15:12 UTC, CapeSathish commented on src/main/java/com/capeelectric/model/Testing.java
> +		@NamedQuery(name = "TestInfoRepository.findByUserNameAndSiteId", query = "select s from Testing s where s.userName=:userName and s.siteId=:siteId"),
Please change the query to be case sensitive

2021-06-22 04:35 UTC, CapeSathish requested changes

2021-06-22 04:35 UTC, CapeSathish commented on src/main/java/com/capeelectric/model/Testing.java
> +		@NamedQuery(name = "TestInfoRepository.findByUserNameAndSiteId", query = "Select s From Testing s Where s.userName=:userName and s.siteId=:siteId"),
Thiru, use some thing like this. select * from testing where userName = ?

2021-06-22 05:24 UTC, CapeSathish approved these changes

2021-06-22 05:25 UTC, merged